### ISSUE TITLE
  EXCEPTION FROM SIMULATION

### ISSUE THREAD

**Issue by aminabs** [messapix/jfxmobile-maven-plugin#2]
Hi there,
I (amin.abbasi63@gmail.com) am working on a javafx project to port on Android. I've created a gattering project to put all maven dependencies inside a single jar file and then, depended on it from another project (dist-project). For this, I create a maven project, depend on any jar artifact required, unpack all dependent jar files using maven-dependency-plugin, and pass them all through retrolambda plugin to fix any probable java 8 dependencies. The final artifact (.jar) now is ready to be depended on from another project: the dist-project. Using jfxmobile-maven-plugin (1.0.0-b2), I try to generate an apk to deploy on android. My android build tool is version 21.1.2 (the same happens with 23.0.2), and my android platform is android-21.

Unfortunately, I'm getting the following exception without further information while trying to build the dist-project. BTW, I am also getting the same exception when using jfxmobile gradle plugin version 1.0.7 (from a gradle project). All comments on solving the issue is appreciated in advance.

**EXCEPTION FROM SIMULATION:**
 **com.android.dx.rop.cst.CstInterfaceMethodRef cannot be cast to** **com.android.dx.rop.cst.CstMethodRef**

  ...at bytecode offset 00000025
  locals[0000]: Lorg/controlsfx/property/BeanProperty;
  stack[top0]: Lorg/controlsfx/property/BeanProperty;
  ...while working on block 0024
  ...while working on method getPropertyEditorClass:()Ljava/util/Optional;
  ...while processing getPropertyEditorClass ()Ljava/util/Optional;
  ...while processing org/controlsfx/property/BeanProperty.class

**Comment by agloria** [comment]
The problem is due to controlsfx. It's not enough to retrolambda in order to use java 8 dependencies. Another requirement is that dependency does not use java 7/8 APIs. For example you cannot use Nio.2. Controlsfx uses a lot of java8 APIs. In your case org.controlsfx.property.BeanProperty class uses getPropertyEditorClass() method not present in android but only in java8.
At the moment the only way to solve the problem is to copy that class in your project and change the code by translating java7/8 code in java6.
In jfxmobile-sample repository there is a project called controlsfx. It allow to run controlsfx sample on android. It contains some few modified controlsfx classes but I don't know how many other classes remain to change.

**Comment by agloria** [comment]
As a side note, if you want to retrolambda all your depemdencies you can use &lt;processJava8Dependencies&gt; in the pom.xml. You don't need to retrolambda each dependencies in a separate project and collect them in a single jar.

**Comment by aminabs** [comment]
Thanks man,
I'll give it a try and let you know.
By the way, I created the gathering project for yet another reason, that is to solve the duplicate class exception which I am facing; I thought that would be the fast solution to both the issues.
Is there any option similar to the android-maven-plugins' extractDuplicates or so?
What about those methods (Java7 or earlier) which are not present in android? For example, If you try to call the javafx task.cancel(true), you will end up with a NoSuchMethodError for a method of a java security class which has to be presented, since it is fairly old. I'm afraid I can't remember the exact class/method name, however, I did report that issue a few days a go.

**Comment by aminabs** [comment]
Unfortunately the  jfxmobile-sample/controlsfx is quite empty. And since its been there for more than 5 month, I do not think it's still in progress.

**Comment by agloria** [comment]
Hi amin,

about duplicate classes: 
there is no problem with this plugin for duplicate classes. For duplicate resources, instead, you can use &lt;packagingOptions&gt; in pom.xml. Example:

&lt;packagingOptions&gt;
         &lt;exclude&gt;META-INF/LICENSE.txt&lt;/exclude&gt;
         &lt;exclude&gt;META-INF/NOTICE.txt&lt;/exclude&gt;
&lt;/packagingOptions&gt;

you can use &lt;pickFirst&gt; instead of &lt;exclude&gt; if you want to pick the first resources in the dependencies instead of exclude them all.
Anyway, if the plugin found duplicate resources during execution it shows you what you should insert into &lt;packagingOptions&gt; element. This save you time since you don't need to find out what duplicate resources are.

about java 7/8 methods:
android almost uses a subset of apache harmony (java 6). JavafxPorts allows you to use the javafx package. If you find NoSuchMethodError by using javafx classes you should report the error here:
http://gluonhq.com/forums/forum/javafxports/
For other packages I dont know if Gluon team has plan to add some of them to the JavafxPort project.

about jfxmobile-sample/controlsfx:
that project is used only to show controlsfx samples on android. It replaces only 3 or 4 classes. It's only shows how to translate java 7/8 code in java 6 code and nothing more. There are other classes that should be replaced but now I'm very busy.

**Comment by aminabs** [comment]
Thank you for your complete explanation.
